#!/bin/bash
# JRB 29jun22
NomIf="enp9s0"
echo

Distro=$(cat /etc/os-release | awk -F '"' NR==1'{print $2}')
echo "Distribución:           $Distro"

# Versión de kernel:
Kernel=$(uname -r)
echo "Versión de kernel:      $Kernel"

# Paquetes instalados:
NumPaq=$(dpkg -l |grep ii -c)
echo "Paquetes instalados:    $NumPaq"

# Uso del Disco
UsoDisco=$(df / | grep / )
TamDisco=$(printf "%.1f\n" $(echo $UsoDisco | awk '{ print $2/1024000}'))
PctDisco=$(echo $UsoDisco | awk '{ print $5}' | sed 's/%//g')
UsoDisco=$(printf "%.2f\n" $(echo $UsoDisco | awk '{ print $3/1024000}'))
echo "Partición:              "$TamDisco" GiB"
echo "Uso de disco:           "$UsoDisco" GiB"
echo "Porcentaje de disco:    "$PctDisco"%"

echo

# Numero de procesos sin contar el título, el script checkpi ps y wc
NumProc=`expr $(ps -e |wc -l) - 4`
echo "Número de procesos:     $NumProc"

# Uso de RAM
TotMem=$(free | grep Mem)
UsoMem=$(printf "%.1f\n" $(echo $TotMem |awk '{print $3/1024}'))
TotMem=$(printf "%.0f\n" $(echo $TotMem |awk '{print $2/1024}'))
PctMem=$(printf "%.1f\n" $(awk -v Uso=$UsoMem -v Tot=$TotMem 'BEGIN { print  ( 100 * Uso / Tot ) }'))
echo "Total de RAM:           "$TotMem" MiB"
echo "Uso de RAM:             "$UsoMem" MiB"
echo "Porcentaje de RAM:      "$PctMem"%"

# Carga del CPU
Carga=$(cat /proc/loadavg | awk '{ print $2}')
echo "Carga 5m:               $Carga"

# Porcentaje uso CPU
UsoCpu=$(printf "%.1f\n" $(grep 'cpu ' /proc/stat | awk '{print ($2+$4)*100/($2+$4+$5)}'))
echo "Uso de CPU:             $UsoCpu%"

# Temperatura del CPU
T=$(printf "%.1f\n" $(cat /sys/class/thermal/thermal_zone0/temp | awk '{print $1/1000}'))
echo "Temperatura del CPU:    $TºC"

echo

# Hostname
HostName=$(hostname)
echo "Nombre del equipo:      $HostName"

# MAC
DirMac=$(cat /sys/class/net/$NomIf/address)
echo "Dirección MAC:          $DirMac"

# IP
DirIp=$(ip a show $NomIf |grep inet|awk NR==1'{print $2}')
echo "Dirección IP/Máscara:   $DirIp"

# Gateway
DirGw=$( ip r |awk NR==1'{print $3}')
echo "Dirección Gateway:      $DirGw"

# Servidor DNS
DirDns=$(cat /etc/resolv.conf |grep nameserver |awk NR==1'{print $2}')
echo "Servidor DNS:           $DirDns"

# Servidor NTP
DirNtp=$(ntpq -p |awk 'FNR==3{print $1}')
echo "Servidor NTP:           "${DirNtp:1:15}
SynNtp=$(timedatectl |grep "System clock synchronized"|awk '{print $4}')
echo "Reloj Sincronizado:     $SynNtp"
echo

# Hora
Hora=$(date '+%X %G-%m-%d')
echo "Hora Actual Local:      $Hora"

# Ultimo inicio
Inicio=$(uptime -s | awk '{print $2,$1}')
echo "Ultimo Inicio:          $Inicio"

# Uptime
UpTime=$(uptime -p)
echo "Uptime:                 $UpTime"

# Ultima actualización:
UltAct=$(ls -Artls /var/lib/dpkg/info |tail -1|awk '{print $9,$8,$7}')
echo "Ultima Actualización:   $UltAct"

# Ultimo login:
UltLog=$(tac /var/log/auth.log | grep -v -a -e cron -e root | \
  grep -m 1 -a "session opened" | awk '{ print $3,$2,$1,$11}')
echo "Ultimo Login:           $UltLog"

echo
