#!/bin/bash
# JRB 29jun22
echo

Distro=$(lsb_release -d | awk '{print $2,$4}')
echo "Distribución GNU/Linux: $Distro"

# Versión de kernel:
Kernel=$(uname -r)
echo "Versión de kernel:      $Kernel"

# Paquetes instalados:
NumPaq=$(dpkg -l |grep ii -c)
echo "Paquetes instalados:    $NumPaq"

# Uso del Disco
PctDisco=$(df / | grep / | awk '{ print $5}' | sed 's/%//g')
echo "Uso de disco:           $PctDisco%"

echo

# Numero de procesos sin contar el título, el script checkpi ps y wc
NumProc=`expr $(ps -e |wc -l) - 4`
echo "Número de procesos:     $NumProc"

# Uso de RAM
PctMem=$(printf "%.1f\n" $(free | grep Mem | awk '{print $3/$2 * 100}'))
echo "Uso de RAM:             $PctMem%"

# Carga del CPU
Carga=$(cat /proc/loadavg | awk '{ print $2}')
echo "Carga 5m:               $Carga"

# Porcentaje uso CPU
UsoCpu=$(printf "%.1f\n" $(grep 'cpu ' /proc/stat | awk '{print ($2+$4)*100/($2+$4+$5)}'))
echo "Uso de CPU:             $UsoCpu%"

# Temperatura del CPU
T=$(printf "%.1f\n" $(cat /sys/class/thermal/thermal_zone0/temp | awk '{print $1/1000}'))
echo "Temperatura del CPU:    $TºC"

echo

# Hostname
HostName=$(hostname)
echo "Nombre del equipo:      $HostName"

# MAC
DirMac=$(cat /sys/class/net/eth0/address)
# ip link show eth0 |grep link/ether|awk '{print $2}'
echo "Dirección MAC:          $DirMac"

# IP
# DirIp=$(hostname -I)
DirIp=$(ip a show eth0 |grep inet|awk '{print $2}')
echo "Dirección IP/Máscara:   $DirIp"

# Gateway
DirGw=$(route |grep default|awk '{print $2}')
echo "Dirección Gateway:      $DirGw"

# Servidor DNS
DirDns=$(cat /etc/resolv.conf |grep nameserver |awk '{print $2}')
echo "Servidor DNS:           $DirDns"

# Servidor NTP
DirNtp=$(timedatectl timesync-status |grep Server|awk '{print $2}')
echo "Servidor NTP:           $DirNtp"
SynNtp=$(timedatectl |grep "System clock synchronized"|awk '{print $4}')
echo "Reloj Sincronizado:     $SynNtp"

echo

# Hora
Hora=$(date '+%X %G-%m-%d')
echo "Hora Actual Local:      $Hora"

# Ultimo inicio
Inicio=$(uptime -s | awk '{print $2,$1}')
echo "Ultimo Inicio:          $Inicio"

# Uptime
UpTime=$(
uptime | awk -F'( |,|:)+' '{d=h=m=0;
 if ($9=="min") {d=$6;m=$8}
 else {
  if ($8=="min") m=$7;
  else {
   if ($7~/^day/) {d=$6;h=$8;m=$9}
   else{h=$6;m=$7}
}}}
{print d+0,"d,",h+0,"hr,",m+0,"min"}')
echo "Uptime:                 $UpTime"

# Ultima actualización:
UltAct=$(ls -Artls /var/lib/dpkg/info |tail -1|awk '{print $9,$8,$7}')
echo "Ultima Actualización:   $UltAct"

# Ultimo login:
UltLog=$(tac /var/log/auth.log | grep -v -e cron -e root | grep -m 1 "session opened" | awk '{ print $3,$2,$1,$11}')
echo "Ultimo Login:           $UltLog"

echo
